export const ADD_TO_WATCHED_LIST = "ADD_TO_WATCHED_LIST";
export const ADD_TO_WATCHED = "ADD_TO_WATCHED";
export const REMOVE_FROM_WATCHED_LIST = "REMOVE_FROM_WATCHED_LIST";
export const REMOVE_FROM_WATCHED = "REMOVE_FROM_WATCHED";
export const MOVE_TO_WATCHED = "MOVE_TO_WATCHED";
